### ISSUE TITLE
all netlify deploys fail after the initial one

### ISSUE THREAD

**Issue by ovsw** [sanity-io/sanity-template-gatsby-blog#43] opened 2019-08-16 21:41 UTC
The build fails when triggering via webhook from Sanity or via repo push. 
In order for the build to pass, you have to trigger a manual deploy from netlify **with clear cache**.

This makes the setup unusable in production, as you manually need to clear the cache for every deploy.

The netlify log is as follows:

```
12:16:45 AM: Installing missing commands
12:16:45 AM: Verify run directory
12:16:45 AM: Executing user command: npm run build-web
12:16:45 AM: > val-app@1.0.0 build-web /opt/build/repo
12:16:45 AM: > (cd studio && SANITY_AUTH_TOKEN=$SANITY_DEPLOY_STUDIO_TOKEN npm run graphql-deploy) && (cd web && npm run build)
12:16:46 AM: > val-app-studio@1.0.0 graphql-deploy /opt/build/repo/studio
12:16:46 AM: > sanity graphql deploy --playground
12:16:46 AM: @sanity/core not installed in current project
12:16:46 AM: Project-specific commands not available until you run `sanity install`
12:16:46 AM: Error: "graphql" is not a sanity command.  See "sanity --help"
12:16:46 AM:     at S.runCommand (/opt/build/repo/node_modules/@sanity/cli/bin/sanity-cli.js:5497:1536)
12:16:46 AM:     at t.exports (/opt/build/repo/node_modules/@sanity/cli/bin/sanity-cli.js:2897:2322)
12:16:46 AM: npm
12:16:46 AM:  ERR! code ELIFECYCLE
12:16:46 AM: npm
12:16:46 AM:  ERR! errno 1
12:16:46 AM: npm ERR!
12:16:46 AM:  val-app-studio@1.0.0 graphql-deploy: `sanity graphql deploy --playground`
12:16:46 AM: npm ERR! Exit status 1
12:16:46 AM: npm ERR!
12:16:46 AM: npm
12:16:46 AM: ERR! Failed at the val-app-studio@1.0.0 graphql-deploy script.
```

I bypassed the issue by creating an environment var in netlify with the deploy token, changing the deploy settings to:
- base directory: web
- Build command: npm run build
- Publish directory: web/public

Also, does this new setup with Sanity Create also build the Studio on Netlify each time I push to repo? Seems a bit overkill...

**Comment by joshuarrr** [comment] 2019-10-05 22:19
I am having a same or similar problem, but I have been unable to bypass.

**Comment by kmelve** [comment] 2019-10-07 15:59
Thanks for reporting, we're looking into it!

**Comment by joshuarrr** [comment] 2019-10-07 16:28
Sorry, appears fixed with latest update!

**Comment by kmelve** [comment] 2019-10-07 17:47
Great!

**Closed by kmelve** 2019-10-07 17:47 UTC

**Comment by dexter-stpierre** [comment] 2019-11-02 22:47
I just started. a site from this template today and I am running into this issue

**Comment by ovsw** [comment] 2019-11-03 07:00
I thought it was just me.

**Comment by kmelve** [comment] 2019-11-03 09:26
I've tried to reproduce it, bot deploying from changes in GitHub, and from the Dashboard widget, but it seems to work. What does the error message in the build log say?

**Comment by dexter-stpierre** [comment] 2019-11-03 13:59
Literally the exact same logs as @ovsw. I searched through some old messages in Slack and it seems like the problem was once fixed by adding `lerna bootstrap` to the build scripts, but it was removed from the template shortly after it was added and the commit message doesn't really give a reason why.. I also tried making a new project and am not seeing it happen on that one, so I don't know what the issue is. I added the `lerna bootstrap` command to my build scripts and it seems to be working now

**Comment by gabytabs** [comment] 2019-12-01 05:11
I am still experiencing this issue. 

Hi @dexter-stpierre I tried it but, it still didn't work for me.

**Comment by nickeblewis** [comment] 2019-12-20 11:06
I am having the same problem and have found that if I re-trigger the build with cache clear, it then works.

**Comment by BoraALAP** [comment] 2019-12-25 21:38
Same here, went to Netlify and from "Trigger Deploy" dropdown I select "Clear Cache and Deploy Site" and it worked

**Comment by BoraALAP** [comment] 2019-12-25 23:40
Now I'm having issue with Website Deployment, It is giving me 
failed during stage 'building site': Build script returned non-zero exit code: 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jaspers-paws-web@1.0.0 build: `gatsby build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jaspers-paws-web@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bora.alap/.npm/_logs/2019-12-25T21_48_30_185Z-debug.log

**Comment by javierfuentesm** [comment] 2020-06-28 21:27
I have the same issue

**Comment by gemouhi** [comment] 2021-01-01 05:36
I try with sudo before sanity command and it worked

**Comment by AndrewTraub** [comment] 2021-03-02 21:56
I'm having the same problem with the kitchen-sink build.

**Comment by ap1969** [comment] 2021-07-28 18:55
I'm also seeing "fsevents not accessible from watchpack:chokidar". I took the 11ty starter, deleted package-lock.json, ran npm install, and now getting the error. It did build before that.
